version: '3'
services:
  frontend:
    image: httpd:latest
    ports:
      - "8081:80"
    networks:
      - app-network
    volumes:
      - ./frontend:/usr/local/apache2/htdocs

  backend:
    build: ./backend
    depends_on:
      - database
    networks:
      - app-network
    environment:
      - APP_ENV=production
      - APP_DEBUG=false

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
